### ISSUE TITLE
lovefield does not work in private browsing

### ISSUE THREAD

**Issue by GeekOnGadgets** [google/lovefield#101]
Hi, 

Thank you for the awesome database :+1: 

Lovefield does not seems to work in a private browsing in safari. Is there a way to make it work out of the box ? or more likely checking if local-storage is available at run time from lovefield and set a flag to not use lovefield ?
Any other approach  or suggestions are welcome. 

Thanks

**Comment by arthurhsu** [comment]
What back store are you using? IndexedDB or WebSQL?

Safari's implementation of IndexedDB is very buggy and does not work in normal mode, not to mention private browsing.

**Comment by arthurhsu** [comment]
Nevermind, just realized Safari does not support any storage in private browsing. We have very little to do with this. If the browser disallows you to persist data, it's the end of the world. You need to use Firebase or Memory.

Shall the library provide you the automatic feedback? I'm leaning toward not to. When you call connect you shall be seeing an exception and handle from there. Personally I'm against over-smartness for exception handling like this.

**Comment by freshp86** [comment]
BTW, Private browsing on Firefox also does not support IndexedDB, see https://bugzilla.mozilla.org/show_bug.cgi?id=781982.

**Comment by GeekOnGadgets** [comment]
Thanks for the reply, appreciated :+1:

**Comment by freshp86** [comment]
FYI, commits https://github.com/google/lovefield/commit/7a56ef9ac28311a155641393609a82b9f2af8713 and https://github.com/google/lovefield/commit/92835d4754d30281273b90507a7ed8691fa3b0b9 are addressing this issue. Specifically the if backstore initialization fails due to an error coming from the browser, this error is now intercepted and converted to an `lf.Exception` with codes 354 for WebSQL, or 361 for IndexedDB, see https://github.com/google/lovefield/blob/master/dist/error_code.json. The error message points to our FAQ for a more in depth explanation.

Remaining item is to update FAQ. Will keep this bug open until then.
