### ISSUE TITLE
Virtual Column

### ISSUE THREAD

**Issue by awsp** [google/lovefield#107]
In MySQL for example, it is possible to create virtual column like this, 
```
SELECT '1' as temp FROM `my_table`
```

Is it possible in lovefield? If so, how could I possibly do it?

Looking at something like this?
```
var e = Db.getSchema().table('Entity');

Db.select(
  e.LastName.as('Last Name'), 
  e.FirstName.as('FirstName'), 
  e.createVirtualColumn('My Virtual Column')
)
.from(e).where(e.LastName.match(/white/i))
.exec().then(function (rows) { 
  console.table(rows);
});
```

**Comment by arthurhsu** [comment]
I don't see computed (aka virtual) columns are something Lovefield needs to support. SQL needs that because store procedures do not have a good way for you to manipulate returned rows. For Lovefield, you have JavaScript and it's easy to manipulate the rows returned.

(One minor caveat is that if you select *, Lovefield returns cache contents directly to you for performance reasons. In that case, you need to clone the row before manipulating it.)

**Comment by awsp** [comment]
I see. Thanks for your reply!
