### ISSUE TITLE
Let user toggle whether to use native Map/Set or not

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#149]
Other frameworks tend to pollute global namespace and define their own Map/Set. Although this is not Lovefield's problem, it would be nice to have an option/flag to disable native Map/Set.

**Comment by freshp86** [comment]
What is the motivation behind this? Currently the code will detect on the fly whether native Map/Set are supported and use them if so, or fallback to custom implementation if not. Is there a good reason to fall back to custom implementation even if Map/Set are supported?

**Comment by freshp86** [comment]
We are actually checking for the existence of `forEach` and `values`, see https://github.com/google/lovefield/blob/master/lib/capability.js#L62-75. Instead of adding a custom flag, how about making those checks more robust by adding checks for all Map/Set methods used by Lovefield. This would automatically force the code to fall back to the polyfil if the users have polluted versions of Map/Set that don't provide the minimum acceptable interface (like the case mentioned at https://groups.google.com/d/msg/lovefield-users/FSrFkaVo9a8/G6wvqstiAwAJ).

**Comment by arthurhsu** [comment]
What I'm more concerned is that the function names are the same but behaves
differently.
Also we advertise ES5 but we use ES6 features without a way to override it.

**Comment by freshp86** [comment]
Can we close this issue? It does not seem that there is an immediate need for this, and the more time passes, the more browsers have fully implemented Map/Set support. Looking at https://kangax.github.io/compat-table/es6/, it seems that the latest versions of all major browsers fully support Map/Set.
