### ISSUE TITLE
data binding demo does nothing

### ISSUE THREAD

**Issue by peterennis** [google/lovefield#163]
![capture17](https://cloud.githubusercontent.com/assets/140737/16169483/4d9c687e-34e5-11e6-90f6-3a5f89b1517d.PNG)

**Comment by arthurhsu** [comment]
Chrome has removed the Object.observe function, which breaks the data binding demo.

**Comment by valioDOTch** [comment]
One could use polyfills instead ;-)
* https://github.com/MaxArt2501/object-observe
* https://github.com/polymer/observe-j

**Comment by freshp86** [comment]
Lovefield latest versions have removed usage of Object.observer. So, although using Polyfils would work, I think the right solution is to use latest version of Lovefield instead.

**Comment by peterennis** [comment]
Thanks for the updates.
However, I am new to this and just learning Lovefield.
Where is the best place to start that can avoid these pitfalls?

**Comment by freshp86** [comment]
1. [Quick start guide](https://github.com/google/lovefield/blob/master/demos/todo/README.md)
2. [Codelab](https://github.com/google/lovefield/blob/master/codelabs/stock_analyzer/docs/codelab.md) Use this version instead of Google IO 2015 website.
3. [Demos](https://github.com/google/lovefield/tree/master/demos)

If a demo is not working, we should fix it, so I don't think there is a generic approach to avoid such pitfalls.
