### ISSUE TITLE
Sourcemap breaks in npm package

### ISSUE THREAD

**Issue by Brooooooklyn** [google/lovefield#180]
![image](https://cloud.githubusercontent.com/assets/3468483/20301253/8573ce10-ab5d-11e6-9bb5-76c5a9c8e8dc.png)

**Comment by freshp86** [comment]
Can you provide steps to reproduce this error?

**Comment by Brooooooklyn** [comment]
I use webpack to bundle my code
you can try:

https://github.com/Brooooooklyn/lovefield-playground/tree/issue/source-map,

here is the webpack.config.js:

```js
const webpack = require('webpack')
const path = require('path')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')

// Webpack Config
const webpackConfig = {
  entry: {
    'main': './src/app.ts',
    'vendor': [ 'lovefield' ]
  },

  output: {
    path: './dist'
  },

  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(true),
    new webpack.optimize.CommonsChunkPlugin({ name: ['main', 'vendor'], minChunks: Infinity }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: `src/index.html`,
      inject: true
    })
  ],

  module: {
    preLoaders: [
      { test: /\.js$/, loader: 'source-map-loader', include: /lovefield|rxjs/ }
    ],
    loaders: [
      { test: /\.ts$/, loader: 'ts' },
      { test: /\.html$/, loader: 'raw-loader' }
    ]
  }

}

const defaultConfig = {
  devtool: 'cheap-module-source-map',
  cache: true,
  debug: true,
  output: {
    filename: '[name].js'
  },

  resolve: {
    root: [ path.join(__dirname, 'src') ],
    extensions: ['', '.ts', '.js']
  },

  devServer: {
    historyApiFallback: true,
    watchOptions: { aggregateTimeout: 300, poll: 1000 }
  },

  node: {
    global: 1,
    crypto: 'empty',
    module: 0,
    Buffer: 0,
    clearImmediate: 0,
    setImmediate: 0
  }
}

const webpackMerge = require('webpack-merge')
module.exports = webpackMerge(defaultConfig, webpackConfig)

```

**Comment by arthurhsu** [comment]
Lovefield source maps are in separated files (e.g. lovefield.min.js.map), and I don't see anywhere in your webpack config mentioned that.

**Comment by Brooooooklyn** [comment]
source-map-loader could handler the separated sourcemap file, It's worked fine with RxJS-5.0.0  which also publish source map file separated:

```ts
{ test: /\.js$/, loader: 'source-map-loader', include: /lovefield|rxjs/ }
```

**Comment by arthurhsu** [comment]
You use webpack-dev-server but not include it as dependency, assuming people have it npm install -g.
I npm start and seeing nothing browsing to localhost 3000. What are the steps to repro the message you see?

**Comment by Brooooooklyn** [comment]
oh, it's my fault. you should checkout to `issue/source-map` branch and run 
```
npm start
```

then ,the warning would display in your terminal

**Comment by arthurhsu** [comment]
I see, your clip of screen shot is very misleading. The actual useful messages are something like

WARNING in ./~/lovefield/dist/lovefield.min.js
Cannot find source file 'third_party/javascript/lovefield/lib/schema/foreign_key_spec.js': Error: Cannot resolve 'file' or 'directory' ./third_party/javascript/lovefield/lib/schema/foreign_key_spec.js in D:\tmp\lovefield-playground\node_modules\lovefield\dist

The problem is that when Lovefield build its dist, it uses the directory structure of the build bot to generate source maps, which includes the source of Lovefield and its dependencies (mainly Closure library). In this case when webpack try to load the source map, it will attempt to refer the files by directory structures that are forged in.

The workaround is to git clone Lovefield to your local computer, and copy the lib/ directory to  your node_modules/lovefield/dist/third_party/javascript. Then the problem will be eased (at least you'll have Lovefield source). The rest are Closure libraries and I don't think you'll be interested. You can clone Closure library and copy it to node_modules/lovefield/dist/javascript/closure if you feel strong about it.

The other option is to use lovefield.js in your debug environment instead. That file is not minified and has all required source code (including Closure library).

**Comment by Brooooooklyn** [comment]
oh, i get it
