### ISSUE TITLE
Need some help with predicate.copy.

### ISSUE THREAD

**Issue by Brooooooklyn** [google/lovefield#185]
I want to implement a function `combine` that take two lovefield `query(select + where(predicate))` and produce a new query that take the original select and `lf.op.or(predicate1, predicate2)`。

So I save the select and predicate separate, and use it in this way:

```ts
class SelectMeta {
  constructor(
   private db: lf.Database,
   public select: lf.query.Select,
   public predicate: lf.Predicate
  ) { }

  getValue() {
    return this.select.clone()
      .where(this.predicate.copy())
      .exec()
  }

  combine(otherSelectMeta: SelectMeta) {
    if (this.select.toSql() !== otherSelectMeta.select.toSql()) {
        throw new TypeError('Could not combine')
    }
    return new SelectMeta(this.select, lf.op.or(this.predicate.copy(), otherSelectMeta.predicate.copy())
  }

  changes(callback: Function) {
    const query = this.select.clone().where(this.predicate.copy())
    this.db.observe(query, callback)
  }
}
```

It works fine when I use `dist/lovefield.js`. But `Predicate.copy` seems not availble in `dist/lovefield.min.js`.

Is it a good way to implement *Combine* like this? Or it is another way to implement *Combine* instead of using  `Predicate.copy` and `Select.clone`

**Comment by freshp86** [comment]
`Predicate#copy()` is not part of Lovefield's public API. It is only meant to be used internally, which is why it is not available in the minified version. I'll study your use case more and respond back if something comes to mind.

**Comment by freshp86** [comment]
So, after thinking a bit, I can't come up with a very elegant way to achieve your `combine()` goal. Essentially you are trying to decompose a Lovefield query after you have created it, and that is not what Lovefield's queries are designed for. If you want to programmatically create queries, you can always hold a reference to the predicates you pass to your queries and and re-use them.

There is an example on how to create a complex predicate programmatically based on user input at [this demo](https://github.com/google/lovefield/blob/master/demos/olympia_db/angular/demo.js#L302).


I am closing this issue since there is no action to be taken. Feel free to move the discussion at the forum. Perhaps if you describe more generically why do you need a `combine()` method, we can figure out an alternative.
