### ISSUE TITLE
Observer throws on diffing rows with Object

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#193]
Original report https://groups.google.com/forum/#!topic/lovefield-users/Vgfo0rWDnH8

Repro: (need small modification: change:any is TypeScript and need fix)

```js
(async function() {
 const builder = lf.schema.create('Test', 1)
 const tableBuilder = builder.createTable('Post')

  tableBuilder.addColumn('_id', lf.Type.STRING)
   .addColumn('object', lf.Type.OBJECT)
   .addColumn('name', lf.Type.STRING)
   .addPrimaryKey(['_id'])

  const database = await builder.connect({
   storeType: lf.schema.DataStoreType.MEMORY
 })

  const table = database.getSchema().table('Post')

  const row = table.createRow({
   _id: '1111',
   object: { a: 1, b: 2 },
   name: 'post 1'
 })

  await database.insert()
   .into(table)
   .values([row])
   .exec()

  const q = database.select()
   .from(table)
   .where(table['_id'].eq('1111'));

  database.observe(q, (change) => {
   console.log(change);
 });

  await database.update(table)
   .set(table['name'], 'post 2')
   .where(table['_id'].eq('1111'))
   .exec();
 // so far it's ok

  await database.update(table)
   .set(table['name'], 'post 3')
   .where(table['_id'].eq('1111'))
   .exec();

  // once JSEngine execute this line, there's an error will be shown in console
})();
```

Exception stack screenshot

<img width="999" alt="screen shot 2017-01-17 at 3 34 27 pm" src="https://cloud.githubusercontent.com/assets/6006159/22044642/83eb5aba-dcca-11e6-96f7-62a2df772e23.png">

**Comment by arthurhsu** [comment]
The bug is in DiffCalculator and only shows when the same row has changed twice.
Reason: DiffCalculator falsely get EQ operator for Object, which is not normal EQ logic (i.e. not deepEquals).  I've created a test file to demo that.

**Comment by freshp86** [comment]
So I did some investigation and figured out why the issue is happening.

For user issued queries, we disallow comparing any OBJECT columns to anything else other than `null` at https://github.com/google/lovefield/blob/master/lib/eval.js#L269. So when our internal algorithm tries to reuse the same column evaluation mechanism to determine whether the row was changed it compares on OBJECT column with its previous value which violates the constraint.

I need to think about what the proper fix would be, but at least now we know why it is happening.
