### ISSUE TITLE
Safari 10.1 - Web Worker

### ISSUE THREAD

**Issue by Hossman333** [google/lovefield#208]
In Safari 10.1, IndexedDB is available inside of Web Workers. However, attempting to run lovefield within a web worker (despite having a proper IndexDB reference in the worker) seems to crash within the `connect()` call on `schemaBuilder`. 

Unfortunately its a browser crash so I don't have many helpful exceptions, however the resulting output looks like OSX memory management is killing the process. This is the result in the `system.log` in OSX Console.

![screen shot 2017-05-01 at 10 25 37 pm](https://cloud.githubusercontent.com/assets/2993997/25604766/54ef0978-2ec3-11e7-914a-b9b281c3e3e5.png)

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Minimal example of using Lovefield</title>
  </head>
  <body>
    <script>
    new Worker('worker.js');
    </script>
  </body>
</html>
```

```javascript
self.importScripts('bower_components/lovefield/dist/lovefield.min.js');


var schemaBuilder = lf.schema.create('todo', 1);
schemaBuilder.createTable('Item').
    addColumn('id', lf.Type.INTEGER).
    addColumn('description', lf.Type.STRING).
    addColumn('deadline', lf.Type.DATE_TIME).
    addColumn('done', lf.Type.BOOLEAN).
    addPrimaryKey(['id']).
    addIndex('idxDeadline', ['deadline'], false, lf.Order.DESC);

var todoDb;
var item;
schemaBuilder.connect().then(function(db) {
  todoDb = db;
  item = db.getSchema().table('Item');
  var row = item.createRow({
    'id': 1,
    'description': 'sploding socks',
    'deadline': new Date(),
    'done': false
  });

  return db.insertOrReplace().into(item).values([row]).exec();
}).then(function() {
  return todoDb.select().from(item).where(item.done.eq(false)).exec();
}).then(function(results) {
  results.forEach(function(row) {
    console.log(row['description']);
    console.log(row['deadline']);
  });
});
```

**Comment by Hossman333** [comment]
Safari Crash report https://gist.github.com/Hossman333/223ae285d66f9c09a1d28ea27d68e121

**Comment by arthurhsu** [comment]
There's really nothing we can do if browser crashes. You should report to Apple and hopefully they'll fix it.

**Comment by splodingsocks** [comment]
@arthurhsu I've been looking a bit more into this, and I'm currently diving through the lovefield codebase trying to find the specific line of code that causes the crash so that I can make a good bug report.

The following code reproduces the crash if run in a Web worker:

```javascript
console.log("Lovefield test: being run from within a Web Worker");
self.importScripts("https://cdnjs.cloudflare.com/ajax/libs/lovefield/2.1.12/lovefield.js");
const lf = self.lf;

var schemaBuilder = lf.schema.create("foo", 1);
schemaBuilder.createTable("Item").addColumn("id", lf.Type.INTEGER); // <- If I comment out this line, the browser doesn't crash.

schemaBuilder.connect().then(function(db) {
  console.log("Success!");
});
```

Commenting out the `createTable` line prevents the crash, which leads me to think that there's a line of code somewhere within the IndexedDB backing store that handles table creation that's causing the crash, but I'm pretty slow at finding it with the good 'ol `debugger;` method.

Is there any chance I could get help locating the line that might be causing the issue, so that we mind find a temporary workaround and make a good Safari bug report?

**Comment by splodingsocks** [comment]
I've added the following line to the minimal case from above:

```
schemaBuilder.setPragma({ enableBundledMode: true });
```

And, in bundled mode, Safari no longer crashes. So it appears that the bug is floating somewhere in the difference between bundled mode and non-bundled mode.

**Comment by splodingsocks** [comment]
@arthurhsu it looks like it might be this line that's causing the crash:
https://github.com/google/lovefield/blob/master/lib/backstore/object_store.js#L115

I'm not sure, but neither the `onsuccess` is not called before Safari crashes. That could just mean that some other async call is crashing the app before the JS tick where that resolution is reached, or it could mean that the native `.getAll` call provided by Safari is crashing behind the scenes in a Web worker.

I notice from the comments that `.getAll` was deemed experimental at the time this code was written. Is that still the case? Could that have something to do with it?

Also, does this seem like a bug with Safari, or a bug with Webkit? I know they are different, but I'm not sure with whom I should file a bug.

Also, another note, the `enableBundledMode` call setting above allows the minimal case to run without crashing, but my main app still crashes. So it must be either that `getAll` is called elsewhere in the code, or that it's some other IDBObjectStore code that's causing the crash.

**Comment by arthurhsu** [comment]
getAll() is in latest IndexedDB spec and we suppose it to work correctly. Seems not the case with Safari and TBH I'm not surprised. My experiences make me to think that it's a Safari issue rather than WebKit (there's not much to do with rendering engine, really. IndexedDB should have been placed under navigator in the first place instead of window).

Lovefield attempts to use getAll() whenever possible to speed up. getAll() is much much faster than traditional cursor loop. In your case you might want to just change https://github.com/google/lovefield/blob/master/lib/backstore/object_store.js#L46 to prohibit use of getAll() until Apple fixes it.

**Comment by splodingsocks** [comment]
Indeed, @arthurhsu, opting out of `getAll` seems to avoid the issue for now. Thank you! I've submitted a bug report to Safari here:

https://bugreport.apple.com/web/?problemID=32297113
