### ISSUE TITLE
Order by string column, case insensitive

### ISSUE THREAD

**Issue by bianchimro** [google/lovefield#218]
My use case is a select query with ordering with respect to a `lf.Type.STRING` column **without** considering case, the equivalent of:

`SELECT * FROM NOTES ORDER BY TITLE COLLATE NOCASE`

or

`SELECT * FROM NOTES ORDER BY LOWER(TITLE);`

I could not generate any of these expressions with lovefield api as:

- there is no support and no future plan to support "COLLATE" in lovefield functions  
- the suggested replacement for the LOWERCASE is to use javascript `toLowerCase` which is fine for selecting/showing data but not for ordering logic (i am using a paginated approach with limit-offset strategy, so "controller-side" ordering is not an option)

(see the [lovefield/sqlite feature parity](https://github.com/google/lovefield/blob/master/docs/sqlite_comparison.md) )

Any suggestion or workaround?

**Comment by arthurhsu** [comment]
Unfortunately this is deliberately not supported by design.

First of all in JS there's not a perfect matching for COLLATE, especially in Unicode case.
Also the LOWERCASE transformation will effectively use a full table scan, which means no index will be used. In this case there's not a benefit for Lovefield to provide APIs doing that.

So the best workaround is to sort the select() results yourselves.
