### ISSUE TITLE
Chances of S3 engine?

### ISSUE THREAD

**Issue by vbresults** [google/lovefield#225]
What are the chances of lovefield introducing S3 objects as a means to store data?

In theory, combining cloudwatch, lambda, and s3 should yield significant savings over say MySQL.

**Comment by valioDOTch** [comment]
I assume you mean Amazon S3 as a DataStoreType?
https://en.wikipedia.org/wiki/Amazon_S3
https://github.com/google/lovefield/blob/master/docs/spec/02_data_store.md

I guess it's rather unlikely that the core lovefield team will implement this, as it is foremost a Google library and Google will hardly ever use any AWS.

**Comment by vbresults** [comment]
Yes, S3 as a DataStoreType.

I see what you mean, but people hardly ever use any Google Cloud Services, if a chart I read is correct it has like 4% market share, and FCM is a big chunk of that I wager.

Like most people I use AWS.  Please consider this, I would start using it in a heartbeat.

**Comment by arthurhsu** [comment]
We welcome contributions/pull requests adding S3 as a store. I'm not 100% sure that's doable since I'm not familiar with it. A back store will require atomic writing from multiple sessions (e.g. memory in JS, IndexedDB). Firebase sort of having it, I can't tell for S3.

As to develop S3 as backend, I don't think I have time nor the interest to do it myself. I will help review the pull requests but that would be it.
