### ISSUE TITLE
Safari <8 support ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [google/lovefield#23]
I have read the docs and tried the demos at http://google.github.io/lovefield/
and indeed LoveField does **NOT** yet support Safari

Is there any chance of officially supporting Safari  via a shim such as : [IndexedDB Polyfill over WebSql](http://nparashuram.com/IndexedDBShim/) or [FaceBook's IndexedDB polyfil](https://github.com/facebookarchive/IndexedDB-polyfill)

Safari 7.1 *theoretically* supports IndexedDB according to [CanIUse.com](http://caniuse.com/#feat=indexeddb)
Apple has officially stated at WWDC 2014 that Safari 8 and iOS 8 will have full support for IndexedDB.

If there won't be any official support then it would be timely for us to provide a patch with Safari support.

**Comment by arthurhsu** [comment]
WebSQL based back store is implemented, since we saw no sign that Apple will fix their IndexedDB bug any time soon. Please consider this is a gap filling solution and we'll remove this backstore as soon as Apple fixes their bugs.

Change 655024eb281ac4793ff78bd3632c6a764f280a41 contains the finalized code.

**Comment by arthurhsu** [comment]
Tested broken on iOS 8 Safari and OSX 10.10 Safari, investigating.

**Comment by arthurhsu** [comment]
Fixed 2e6ba5f70c1d8754d45fa2d5d8b1620919a87c08
