### ISSUE TITLE
Errors should show messages, not URLs

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [google/lovefield#241]
I really don't know why, when Lovefield throws exceptions, it has to give me the URL of a plain-text error message. I believe Lovefield should be able to AJAX GET the actual error message. I'm willing to fix this, but really don't know where to begin with unit testing.

I'm trying to turn the exception fragment
`
code: 202,
message: "http://google.github.io/lovefield/error_lookup/src/error_lookup.html?c=202&p0=trainings.dates"
`
into
`
code: 202,
message: "Constraint error: (202) Attempted to insert NULL value to non-nullable field trainings.dates."
`
Please bear in mind that the exception above is only an example. Please reread the first paragraph of my message if you do not understand what I take issue with. Thank you!

**Comment by arthurhsu** [comment]
This is by design. The reason is to reduce the size of generated file (it effectively reduces 20KB gzipped or so, I forgot the exact numbers). For our biggest customer GMail, adding 20KB per day means tera/peta bytes more traffic per year, and that's not a good thing.

Why we don't do AJAX GET? There are security concerns.

As a result, this is a compromise to sacrifice developer convenience to have a smaller, more secure library.
