### ISSUE TITLE
Will lovefield get long term support?

### ISSUE THREAD

**Issue by snietert** [google/lovefield#266]
Hallo @arthurhsu,

I have the requirement of offline storage of larger amounts of data and I found lovefield as an abstraction on top of IndexedDB. Amazing work!

But considering that the official lovefield repo has seen not many updates over the last 4 years, I was wondering ... is lovelfield future proof? Browsers do change. Will lovefield be adapted to browser changes continuously? I have to make sure our software also works in future browser versions. Will google maintain lovefield in the future? Is it used in official google products?

I also saw that there is a lovefield-ts version (https://github.com/arthurhsu/lovefield-ts) Could that be an alternative option for me?

Sorry, I would have loved to label this as a question but did not see how.

Would be happy to hear from you. Thanks a lot in advance!

**Comment by arthurhsu** [comment]
Lovefield is under long-term maintenance but there will be no new features (i.e. feature freeze). G-Mail is using it and as long as G-Mail is still using it we'll keep supporting it. There are not many updates because Lovefield has very few bugs (G-Mail only managed to find 7 bugs during their whole usage, and they are all fixed of course).

As to Lovefield-TS port, it's my personal project and not sponsored by Google. I do welcome contributions to that project. I did pretty thorough testing on that one, but again, use at your own risk as suggested on the Apache-2 License. The reason I did Lovefield-TS port is because TypeScript is much easier to debug and maintain in the long run compared to Closure-based JS code.
