### ISSUE TITLE
lovefields/demo/scrum broken

### ISSUE THREAD

**Issue by tonydiep** [google/lovefield#267]
Following readme.md instructions: 
$  gulp debug
results in 
ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/home/tonydiep/Projects/lovefield/demos/scrum/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/tonydiep/Projects/lovefield/demos/scrum/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/tonydiep/Projects/lovefield/demos/scrum/node_modules/graceful-fs/fs.js:1:37)
...

**Comment by tonydiep** [comment]
* Figured out the issue is the scrum and todo demos do not work with Node 12. 
* Fixed it by using Node 10

**Comment by NerdyDeedsLLC** [comment]
I wanna toss this in for any who may follow after with the same problem , followed by the corollary problem I just resolved:

**If you are on a Silicone Mac and cannot install v.10 of node using NVM...**
The problem here is one of the arm64 architecture is incompatible with older versions of Node.

From the terminal, run the following command:
```arch -x86_64 zsh```

...this tells Rosetta to emulate the older, x86 architecture. NOW run your `nvm install 10`. NVM will successfully install Node 10. The GOOD news is, once installed, a simple `nvm use 10` will suffice, even once you've restarted your terminal (e.g. you don't need to switch back to the x86 architecture each time. Just make sure you're running Node 10.

Hope this helps another Mac early adopter.
