### ISSUE TITLE
Missing `goog` in `dist/lovefield.min.js` v2.0.59

### ISSUE THREAD

**Issue by sanemat** [google/lovefield#60]
`lovefield-spac` generates a file like below:
```js
goog.provide('mydatabase.row.Configs');
goog.provide('mydatabase.ConfigsDbType');
goog.provide('mydatabase.ConfigsType');
(snip)
```

But `dist/lovefield.min.js` does not have `goog` object, so this brings `Uncaught ReferenceError: goog is not defined`.

E.g. `v2.0.52` has `goog` object, `v2.0.59` does not have `goog`.

**Comment by freshp86** [comment]
Hi.
code generated by lovefield-spac is not supposed to be used with lovefield.min.js (or lovefield.js). lovefield-spac is targeting users who would like to type check and compile the code themselves (with JS Compiler). In order to work it requires to take the generated files and lovefield source files (under lib/) and compile them together.

The fact that v2.0.52 had "goog" defined, was just accidental, because at the time we had not minified and obfuscated lovefield.min.js, see changelog at https://github.com/google/lovefield/blob/master/dist/CHANGELOG.md, where at version 2.0.54 lovefield.min.js size was reduced to 114kb.

Unfortunately currently none of the demos under demos/ is using lovefield-spac generated code. We should probably add one such that the correct usage of lovefield-spac can be better understood.

**Comment by sanemat** [comment]
@freshp86 I get it! Thanks!
