### ISSUE TITLE
Foreign key constraints are not enforced

### ISSUE THREAD

**Issue by arthurhsu** [google/lovefield#8]
Need to implement such constraints for INSERT and UPDATE queries, also honor the "cascade" keyword in the schema.

**Comment by freshp86** [comment]
Foreign key constraints have been implemented for all types of queries (insert, insertOrReplace, update and delete). All foreign key constraints are currently treated as RESTRICT (see explanation at https://github.com/google/lovefield/blob/master/docs/spec/08_referential_integrity.md#821-restrict).

I am closing this issue since there is already a bug to track the CASCADE work, see https://github.com/google/lovefield/issues/14.
