### ISSUE TITLE
Look at this Lovefield benchmark, why is it so slow?

### ISSUE THREAD

**Issue by robertbaker** [google/lovefield#82]
https://github.com/digital-synapse/lovefield-typescript-performance-test

**Comment by freshp86** [comment]
Can you post the numbers here? How much time it takes for how many insertions/deletions? Also how about selections?

**Comment by robertbaker** [comment]
![2015-09-15](https://cloud.githubusercontent.com/assets/907301/9886733/9ede0a68-5ba0-11e5-8c05-05fb3262f89f.png)

**Comment by freshp86** [comment]
Thanks for the numbers. After taking a brief look at your code, noticed an odd pattern. Why are you connecting to the DB multiple times? This should only be done once, and re-use the same DB connection for all the queries. I expect this will drop all the times you are reporting.

**Comment by digital-synapse** [comment]
Thanks we updated the tests to remove the database connections and the performance has improved considerably especially for selects.

![image](https://cloud.githubusercontent.com/assets/8227453/9888182/7f281684-5ba8-11e5-8f5d-befb261a5881.png)

one thing that i noticed was that the deletes are suspiciously quick for indexedDB. Almost as if the method is calling resolve before the promise has been fulfilled.

**Comment by digital-synapse** [comment]
Thanks we updated the tests to remove the database connections and the performance has improved considerably especially for selects.

![image](https://cloud.githubusercontent.com/assets/8227453/9888353/769105ca-5ba9-11e5-9e5a-57041fe71953.png)

one thing that i noticed was that the deletes are suspiciously quick for indexedDB. Almost as if the method is calling resolve before the promise has been fulfilled.

**Comment by freshp86** [comment]
Deletes indeed look suspiciously quick. The timings reported here do not match the ones in Lovefield's perf dashboard, see https://google.github.io/lovefield/dashboard/src/dashboard.html (specifically see test case called "PK-based table scan: Delete". It almost seems as if you are deleting from an empty table. Can you verify that before you delete, the table is indeed populated?

I don't have time to try this myself today, but maybe tomorrow. If you could update your example with your latest changes (single DB connection), that would help.

**Comment by digital-synapse** [comment]
thanks. updated the [example code](https://github.com/digital-synapse/lovefield-typescript-performance-test)

**Comment by freshp86** [comment]
Took another look at the code, lovefield-tests.ts specifically. Simultaneous connections to WEB_SQL and INDEXED_DB does not work as you expect, so don't do that. Here are two suggestions.

1) Do the connections one at a time, don't interleave them together. For example change your sequence of queries to
```
 sequence(
            [testSelectPredicate, db],
            [testSelect, db],
            [testInsert, db],
            [dropTable, db],
            [testInsertBatch, db],
            [dropTable, db],
        );
```
I am also a bit confused on why selection happens before anything has been inserted to the DB.

2) If you still want to use two simultaneous connections (one to IDB and one to WEB_SQL), you must use different schema builders (and the shemas should have different names). One schema object is supposed to be used with a single backing store only. I hope this helps.

**Comment by digital-synapse** [comment]
Thanks. Right connecting to both of the backing stores at the same time were causing the issues with delete. I've changed the tests to run through the tests and one suprise. We can see now that delete is taking some time to complete.

![image](https://cloud.githubusercontent.com/assets/8227453/9891530/aaecfad8-5bbb-11e5-808d-826fa5639ef0.png)

everything looks fine. One curious thing about the webSQL backend. the select seems to be much faster when there is a predicate given. 

btw: the answer to your question about selection happens before anything has been inserted is because the sequence function acceps an array and uses pop to resolve the promises sequentially. I added an array.reverse so that the sequence can be given in the right order. less confusing that way.

**Comment by robertbaker** [comment]
@freshp86 Do the new numbers look accurate or is there more fine tuining @digital-synapse can do?

**Comment by freshp86** [comment]
I can probably help more if I can run the code locally. I tried `npm install` and `gulp dev`, but I got some errors after loading the page. I am probably missing some step, let me know.

Looking at the code, I still don't think it is entirely correct. Repeating from my previous comment:
**Shouldn't call connect() twice on the same schemaBuilder instance**. I know that the API allows it (does not throw any error), but the results are not as expected. If you need more details you can see this lines https://github.com/google/lovefield/blob/master/lib/schema/builder.js#L246, where it is clear that your two separate DB connections are re-using Lovefield's "global" object (an object holding all singleton services). The two connections should not be sharing any internal data-structures.

I suggest something as follows
```
var schemaBuilderIdb: lf.schema.Builder = lf.schema.create('todo_idb', 1);
schemaBuilder.createTable('Item').
    addColumn('id', lf.Type.INTEGER).
    /** .... more calls to addColumn() here */

var schemaBuilderWebSql: lf.schema.Builder = lf.schema.create('todo_websql', 1);
/** .... build schema again from scratch here*/

schemaBuilderIdb.connect({storeType: lf.schema.DataStoreType.INDEXED_DB})........
schemaBuilderWebSql.connect({storeType: lf.schema.DataStoreType.WEB_SQL})........
```

I know this is a bit tedious, but keep in mind that opening simultaneous connections to WebSQL and IDB is not a main use case, it's not useful in general, although I see why it is useful for performance testing.

Regarding whether more fine tuning, yes there is more room. Specifically, need to add index for the columns that matter (the ones used in the most frequent select queries). In the example code, there is an index for "deadline", but the select query only cares about "id" and "done". Adding index on any of those columns should make queries with predicates much faster. You can inspect the execution plan by calling the `explain()` method an any query. For example
```
var q = db.select().from(dummyItem).where(lf.op.and(id.gt(-1), done.eq(false));
console.log(q.explain()); // See whether any index is being used, if there are full tables scans etc.
```

**Comment by digital-synapse** [comment]
npm install
jspm install
gulp dev

should do the trick

**Comment by freshp86** [comment]
I am able to run the code now. Had to config jspm with my github credentials.
Can you update the code with the latest changes? I still see the previous version. Once you do, I can compare the numbers with the ones you posted and see if there is anything else to be changed.

**Comment by digital-synapse** [comment]
sorry. forgot to push the changes. should be up to date now.

**Comment by freshp86** [comment]
I run the latest code locally. Here are some observations. First the numbers from a single run (not averaged).

```
lovefield:IndexedDB 1 insert 50000 rows 6942ms
lovefield:IndexedDB deleting 50000 rows 2096ms
lovefield:IndexedDB 50000 inserts 9932ms
lovefield:IndexedDB 1 select 50000 rows 62ms
lovefield:IndexedDB 1 select 50000 rows with predicate 99ms
```

* insertions/deletions timings seem consistent with the timings in Lovefield's performance dashboard. It's  relatively slow because of talking to IndexedDB backend. Feel free to compare with the `lf.schema.DataStoreType.MEMORY` to get an idea of the overhead that is added by IDB/WebSQL. Here are the numbers I got for MEMORY backstore
```
lovefield:Memory 1 insert 50000 rows 571ms
lovefield:Memory deleting 50000 rows 533ms
lovefield:Memory 50000 inserts 3476ms
lovefield:Memory 1 select 50000 rows 47ms
lovefield:Memory 1 select 50000 rows with predicate 87ms
```

* SELECT * FROM timings also seem consistent with the dashboard.
* Now for `selectWithPredicate`:
   You are selecting all rows from the database, using a predicate which all rows satisfy. This explains why this query is slower than the previous one. The predicate acts as pure ovrehead on the query (does not filter out any results). It causes the index on "id" to be used, but using an index is not helpful when there is no selectivity benefits (pathological case). If you really want to see the benefits of using the index, try selecting a subset of the rows (something like item.id.between(100, 200), or item.id.eq(2500)).

Regarding the pathological case I am talking above, Lovefield could potentially improve it by not choosing to use the index if selectivity is below a certain percentage. This is a practice used by other DBMSs as far as I know.

**Comment by digital-synapse** [comment]
I agree. Thanks for your help. I will leave the perfomance tests on github in case anyone else wants to run them.

**Comment by freshp86** [comment]
Last thing to note: You can try lovefield.min.js for even better performance. lovefield.js is a debug version and besides not being minified and optimized by the Closure compiler, it also has a few assertions that can slow things down.
